name: monomer
version: 0.1.0.0
github: fjvallarino/monomer
license: BSD3
author: Francisco Vallarino
maintainer: fjvallarino@gmail.com
copyright: 2018 Francisco Vallarino

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: GUI Library
category: GUI
description:
  Monomer is an easy to use, cross platform, GUI library for writing Haskell
  applications.

  It provides a framework similar to the Elm Architecture, allowing to create
  GUIs functionally using an extensible set of widgets.

  You can find the available widgets in @Monomer.Widgets@.

  Please see the README on Github at <https://github.com/fjvallarino/monomer#readme>

default-extensions:
- OverloadedStrings

dependencies:
- async
- attoparsec
- base >= 4.7 && < 5
- bytestring
- bytestring-to-vector
- containers
- data-default
- exceptions
- extra
- formatting
- http-client
- JuicyPixels
- lens
- mtl
- nanovg
- OpenGL
- process
- safe
- sdl2
- stm
- text
- text-show
- time
- transformers
- unordered-containers
- vector
- wreq

library:
  source-dirs: src
  include-dirs: cbits
  install-includes: fontmanager.h
  c-sources:
  - cbits/dpi.c
  - cbits/fontmanager.c
  - cbits/glew.c
  cc-options:
  - -fPIC
  ghc-options:
  - -fwarn-incomplete-patterns
  when:
    - condition: os(windows)
      then:
        extra-libraries: glew32
      else:
        extra-libraries: GLEW

executables:
  monomer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T

    dependencies:
    - ekg
    - lens
    - monomer

  books:
    main: Main.hs
    source-dirs: examples/books
    ghc-options:
    - -threaded
    dependencies:
    - aeson
    - lens
    - monomer
    - text-show
    - wreq

  generative:
    main: Main.hs
    source-dirs: examples/generative
    ghc-options:
    - -threaded
    dependencies:
    - lens
    - monomer
    - random
    - text-show

  ticker:
    main: Main.hs
    source-dirs: examples/ticker
    ghc-options:
    - -threaded
    dependencies:
    - aeson
    - lens
    - monomer
    - scientific
    - text-show
    - websockets
    - wuss

  todo:
    main: Main.hs
    source-dirs: examples/todo
    ghc-options:
    - -threaded
    dependencies:
    - lens
    - monomer
    - text-show

  tutorial:
    main: Main.hs
    source-dirs: examples/tutorial
    ghc-options:
    - -threaded
    dependencies:
    - lens
    - monomer
    - random
    - text-show
    - time

tests:
  monomer-test:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
    - -threaded
    - -fwarn-incomplete-patterns
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - call-stack
    - directory
    - monomer
    - hedgehog
    - hspec
    - HUnit
    - silently
